schedules:
- cron: '30 3 * * *'
  displayName: 'Execução diária 00:30 BRT'
  branches:
    include:
    - azure-pipelines
  always: true

trigger:
  branches:
    include:
    - azure-pipelines

pr:
  branches:
    include:
    - dev

pool:
  name: Agente_Azure-pipelines

variables:
- group: Segredos_PATS 

steps:
- checkout: self
  persistCredentials: true

- script: python --version
  displayName: 'Verificar versão do Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependências'

- script: python Extracao_e_Insercao/gerar_lote_e_rodar.py
  displayName: 'Executar: gerar_lote_e_rodar.py'

- script: python ETL/etl_ingest.py
  displayName: 'Executar: etl_ingest.py'

- script: python ETL/pricing.py
  displayName: 'Executar: pricing.py'

- powershell: |
    # Configura o nome e e-mail do autor do commit
    git config user.name "pipeline-bot"
    git config user.email "pipeline-bot@example.com"

    # Adiciona o diretório de fontes como um diretório seguro para o Git
    git config --global --add safe.directory "$(Build.SourcesDirectory)"
    
    git remote set-url origin https://x-access-token:$(GITHUB_PAT)@github.com/pedrofamaral/Precificacao_dinamica.git
    
    git fetch origin $(Build.SourceBranchName)
    git checkout -B $(Build.SourceBranchName) origin/$(Build.SourceBranchName)
    
    if (git status --porcelain) {
      git add -A
      git commit -m "Auto: atualizações $(Build.BuildNumber) [skip ci]"
      git push origin HEAD:$(Build.SourceBranchName)
      Write-Host "Alterações commitadas e enviadas com sucesso."
    } else {
      Write-Host "Nenhuma alteração para commitar."
    }
  displayName: 'Commit e Push de alterações (GitHub)'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # Não executa em Pull Requests
  env:
    GITHUB_PAT: $(GITHUB_PAT)